[profile.default]
optimizer_runs = 1_000_000
verbosity = 1
via_ir = true
remappings = [
    "ds-test/=lib/ds-test/src/",
    "solmate/=lib/solmate/src/",
    "forge-std/=lib/forge-std/src/",
]
solc = "0.8.17"

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
# Mainnets
mainnet = "https://rpc.ankr.com/eth"
arbitrum = "https://arb1.arbitrum.io/rpc"
base = "https://1rpc.io/base"
blast = "https://rpc.blastapi.io"
optimism = "https://optimism.drpc.org"
polygon = "https://rpc.ankr.com/polygon"

# Testnets
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
berachain-artio = "https://artio.rpc.berachain.com"
base-sepolia = "https://rpc.notadegen.com/base/sepolia"
blast-sepolia = "https://sepolia.blast.io"
optimism-sepolia = "https://sepolia.optimism.io"
sepolia = "https://rpc.ankr.com/eth_sepolia"
mevm-m1 = "https://mevm.devnet.m1.movementlabs.xyz/v1"
