[profile.default]
optimizer_runs = 1_000_000
verbosity = 1
via_ir = true
remappings = [
    "ds-test/=lib/ds-test/src/",
    "solmate/=lib/solmate/src/",
    "forge-std/=lib/forge-std/src/",
]
solc = "0.8.17"

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4
